# Site settings
title: katoro's Develoment Blog
description: Welcome
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://katoro.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: katoro
user_description: SW Engineer
user_title: 
email: katoro@gmail.com
twitter_username: 
github_username:  katoro
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
